### PR TITLE
return early in status check if branch is not promotion

### LINKED ISSUE #46: Skip status check on manual PR
`StatusCommand()` fails when doing manual PR to the GitOps repo, causing build validation in Azure DevOps to fail.

The following error occurs:

```
ERROR: failed getting pr for current branch: invalid metadata: "<PR Description>"
```

We should most likely add a check early to see if this is a GitOps promotion PR or not and allow it through.

My suggestion is to either put all PRs from GitOps promotion to a specific path - like `gitops-promotion/<old-path>` or add something like a tag in the description or title, like `[gitops-promotion] <old title>` and check for these before continuing.

@NissesSenap @phillebaba what would you prefer?

### PR DESCRIPTION
**Pull request by dachrillz**
Fixes #46

### CODE REVIEW

File: pkg/git/git.go [hunk 1]
```diff
@@ -9,6 +9,7 @@ import (
 const DefaultUsername = "git"
 const DefaultRemote = "origin"
 const DefaultBranch = "main"
+const PromoteBranch = "promote/"
```
Comment (simongottschlag) [inline pkg/git/git.go:12]:
```suggestion
const PromoteBranchPrefix = "promote/"
```

**Review by simongottschlag — APPROVED** [review]
Looking good @dachrillz!! 😊🥇🎉⭐️
